/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Estado del servicio y del snapshot cargado.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description KPIs del panel: alertas activas, casos rojos, riesgo organizacional y tendencia diaria.
         */
        get: operations["overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Employees
         * @description Cola de triage priorizada (usuarios anonimizados U-####).
         */
        get: operations["employees_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Employee Risk
         * @description Serie temporal de la puntuación de riesgo (últimos `days` días disponibles).
         */
        get: operations["employee_risk_employees__employee_id__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Employee Explanation
         * @description Top-5 SHAP del día, con el valor del usuario vs. su promedio personal y vs. su peer group.
         *
         *     Solo hay explicación para días con alerta: los verdes son registro pasivo.
         */
        get: operations["employee_explanation_employees__employee_id__explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Employee Activity
         * @description Resumen de autenticaciones del día: destinos nuevos, fallos, NTLM y horario.
         */
        get: operations["employee_activity_employees__employee_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Case Feedback History
         * @description Historial de decisiones del analista sobre un caso.
         *
         *     Cierra la trazabilidad que exige un perfil de cumplimiento: toda decisión sobre
         *     una cuenta queda registrada y es consultable.
         */
        get: operations["case_feedback_history_cases__case_id__feedback_get"];
        put?: never;
        /**
         * Case Feedback
         * @description Registra la decisión del analista (falso positivo / investigar / escalar).
         *
         *     Cierra el ciclo human-in-the-loop: ninguna acción sobre la cuenta es automática, y la decisión
         *     queda trazada para auditoría.
         *     Nota de despliegue: en planes gratuitos el almacenamiento es efímero.
         */
        post: operations["case_feedback_cases__case_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assistant Health
         * @description Indica si el asistente conversacional está configurado (DEEPSEEK_API_KEY presente).
         */
        get: operations["assistant_health_assistant_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assistant Chat
         * @description Asistente conversacional: guía al usuario y responde preguntas sobre los datos
         *     consultando el modelo mediante function calling (DeepSeek).
         *
         *     La API key vive solo en el backend. Sin ella, degrada con 503 explícito.
         */
        post: operations["assistant_chat_assistant_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inference/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inference Score
         * @description Inferencia REAL sobre un usuario-día: ejecuta el modelo en vivo.
         *
         *     Demuestra el flujo completo frente al snapshot precomputado. Requiere los artefactos
         *     serializados; si no están presentes responde 503 en lugar de fallar de forma opaca.
         */
        post: operations["inference_score_inference_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Actividad */
        Actividad: {
            /** Id */
            id: string;
            /** Day */
            day: number;
            /** N Eventos */
            n_eventos: number;
            /** N Dst */
            n_dst: number;
            /** N Destinos Nuevos */
            n_destinos_nuevos: number;
            /** N Origenes Nuevos */
            n_origenes_nuevos: number;
            /** N Fallos */
            n_fallos: number;
            /** Ratio Ntlm */
            ratio_ntlm: number;
            /** N Fuera Horario */
            n_fuera_horario: number;
            ego_graph?: components["schemas"]["EgoGraph"] | null;
        };
        /** ChatIn */
        ChatIn: {
            /**
             * Messages
             * @description Historial de la conversación, sin el system.
             */
            messages: components["schemas"]["MensajeChat"][];
        };
        /** ChatOut */
        ChatOut: {
            /** Reply */
            reply: string;
            /**
             * Tools Used
             * @description Herramientas de datos que el asistente consultó
             */
            tools_used?: string[];
        };
        /** ContribucionShap */
        ContribucionShap: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /**
             * Contribucion
             * @description Aporte SHAP (signo = dirección)
             */
            contribucion: number;
            /** Valor */
            valor: number;
            /**
             * Promedio Personal
             * @description Media histórica del propio usuario
             */
            promedio_personal?: number | null;
            /**
             * Promedio Peer
             * @description Media de su peer group ese día
             */
            promedio_peer?: number | null;
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "falso_positivo" | "investigar" | "escalar";
        /**
         * EgoGraph
         * @description Nodos del mini-grafo usuario→computadoras que dibuja la vista de investigación.
         */
        EgoGraph: {
            /**
             * Nodos Nuevos
             * @description Destinos tocados por primera vez (en rojo)
             */
            nodos_nuevos: string[];
            /**
             * Nodos Conocidos
             * @description Destinos ya conocidos (en gris)
             */
            nodos_conocidos: string[];
            /** N Nuevos */
            n_nuevos: number;
            /** N Conocidos */
            n_conocidos: number;
            /** N Historicos Totales */
            n_historicos_totales: number;
            /**
             * Conocidos Truncados
             * @description True si se recortó la lista por legibilidad
             */
            conocidos_truncados: boolean;
        };
        /** EmpleadoCola */
        EmpleadoCola: {
            /**
             * Id
             * @description ID anonimizado
             * @example U-0737
             */
            id: string;
            /** Risk Max */
            risk_max: number;
            level: components["schemas"]["Nivel"];
            /** Dia Pico */
            dia_pico: number;
            /** N Dias Alerta */
            n_dias_alerta: number;
            /**
             * Motivo
             * @description Razón principal en una línea, derivada del top SHAP
             */
            motivo: string;
            /**
             * Es Comprometida
             * @description Ground truth (demo académica)
             */
            es_comprometida: number;
        };
        /** Explicacion */
        Explicacion: {
            /** Id */
            id: string;
            /** Day */
            day: number;
            /** Risk */
            risk: number;
            level: components["schemas"]["Nivel"];
            /** Prob */
            prob: number;
            /** Motivo */
            motivo: string;
            /** Top Shap */
            top_shap: components["schemas"]["ContribucionShap"][];
        };
        /** FeedbackIn */
        FeedbackIn: {
            decision: components["schemas"]["Decision"];
            /**
             * Analista
             * @default anonimo
             */
            analista: string;
            /** Dia */
            dia?: number | null;
            /** Nota */
            nota?: string | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Registrado */
            registrado: boolean;
            /** Case Id */
            case_id: string;
            decision: components["schemas"]["Decision"];
            /** Timestamp */
            timestamp: string;
        };
        /**
         * FeedbackRegistro
         * @description Una decisión registrada, tal como se consulta en el historial del caso.
         */
        FeedbackRegistro: {
            /** Case Id */
            case_id: string;
            decision: components["schemas"]["Decision"];
            /** Analista */
            analista: string;
            /** Timestamp */
            timestamp: string;
            /** Dia */
            dia?: number | null;
            /** Nota */
            nota?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Snapshot Cargado */
            snapshot_cargado: boolean;
            /** Periodo Dias */
            periodo_dias: number[];
            /** Usuarios */
            usuarios: number;
        };
        /** InferenciaIn */
        InferenciaIn: {
            /**
             * Employee Id
             * @example U-0737
             */
            employee_id: string;
            /**
             * Day
             * @example 29
             */
            day: number;
        };
        /** InferenciaOut */
        InferenciaOut: {
            /** Id */
            id: string;
            /** Day */
            day: number;
            /** Risk Score */
            risk_score: number;
            level: components["schemas"]["Nivel"];
            /** Prob */
            prob: number;
            /** Anomaly */
            anomaly: number;
            /** Motivo */
            motivo: string;
            /** Top Shap */
            top_shap: components["schemas"]["ContribucionShap"][];
            /**
             * Fuente
             * @description 'modelo_en_vivo' o el motivo de la degradación
             */
            fuente: string;
        };
        /** KpisSoc */
        KpisSoc: {
            /** Alertas Por Dia */
            alertas_por_dia: number;
            /** Casos Rojos Por Dia */
            casos_rojos_por_dia: number;
            /**
             * Pct Falsos Positivos
             * @description Sobre las alertas emitidas (ground truth)
             */
            pct_falsos_positivos: number;
            /** Cuentas Comprometidas Detectadas */
            cuentas_comprometidas_detectadas: number;
            /** Cuentas Comprometidas Totales */
            cuentas_comprometidas_totales: number;
            /** Carga Revisable */
            carga_revisable: string;
            /**
             * Tiempo Resolucion Medio
             * @description Requiere telemetría real de analistas; null en la demo (no se estima)
             */
            tiempo_resolucion_medio?: number | null;
        };
        /** MensajeChat */
        MensajeChat: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * Nivel
         * @enum {string}
         */
        Nivel: "verde" | "naranja" | "rojo";
        /** Overview */
        Overview: {
            /**
             * Alertas Activas
             * @description Usuario-días en nivel naranja o rojo
             */
            alertas_activas: number;
            /** Casos Rojos */
            casos_rojos: number;
            /** Usuarios Monitoreados */
            usuarios_monitoreados: number;
            /**
             * Riesgo Organizacional
             * @description Riesgo medio 0-100 del periodo
             */
            riesgo_organizacional: number;
            /**
             * Cuentas Comprometidas Periodo
             * @description Ground truth del red team (solo para la demo académica)
             */
            cuentas_comprometidas_periodo: number;
            /** Tendencia */
            tendencia: components["schemas"]["PuntoTendencia"][];
            /**
             * Tendencia Por Cluster
             * @description Riesgo por rol conductual (vista ejecutiva)
             */
            tendencia_por_cluster?: components["schemas"]["PuntoCluster"][];
            kpis_soc?: components["schemas"]["KpisSoc"] | null;
        };
        /** PuntoCluster */
        PuntoCluster: {
            /** Peer Cluster */
            peer_cluster: number;
            /** Day */
            day: number;
            /** Riesgo Medio */
            riesgo_medio: number;
            /** Alertas */
            alertas: number;
            /** Usuarios */
            usuarios: number;
        };
        /** PuntoRiesgo */
        PuntoRiesgo: {
            /** Day */
            day: number;
            /** Risk */
            risk: number;
            level: components["schemas"]["Nivel"];
        };
        /** PuntoTendencia */
        PuntoTendencia: {
            /** Day */
            day: number;
            /** Alertas */
            alertas: number;
            /** Riesgo Medio */
            riesgo_medio: number;
        };
        /** SerieRiesgo */
        SerieRiesgo: {
            /** Id */
            id: string;
            /** Peer Cluster */
            peer_cluster: number;
            /** Timeline */
            timeline: components["schemas"]["PuntoRiesgo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    overview_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    employees_employees_get: {
        parameters: {
            query?: {
                sort?: string;
                /** @description Filtra por nivel del semáforo */
                level?: components["schemas"]["Nivel"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpleadoCola"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    employee_risk_employees__employee_id__risk_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerieRiesgo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    employee_explanation_employees__employee_id__explanation_get: {
        parameters: {
            query: {
                date: number;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explicacion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    employee_activity_employees__employee_id__activity_get: {
        parameters: {
            query: {
                date: number;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actividad"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    case_feedback_history_cases__case_id__feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRegistro"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    case_feedback_cases__case_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_health_assistant_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    assistant_chat_assistant_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inference_score_inference_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InferenciaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenciaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
